### ISSUE TITLE
in order to run `run_agent.py` in windwos. what virtual python env version number should i choose ? 

### ISSUE THREAD

**Issue by q2333gh** [BurgerNight/Dota2-DragonChess-AI#2]

**Comment by q2333gh** [comment]
i tried venv of py3.6.5 or py3.12.4  all not compatible

**Comment by BurgerNight** [comment]
I am working on python 3.8.  What is your error message?
To run without using python, you can download the executable version of the program from the release.

**Comment by jsqu4lo** [comment]
I am working on python 3.9
